apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: admin
    database: website-monitor
    basicAuth: false
    isDefault: true
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: website-monitor
      httpMode: POST
    secureJsonData:
      token: mytoken